### ISSUE TITLE
Detected by WD

### ISSUE THREAD

**Issue by NightFuryPrime** [LNodesL/NCrypt#2]
Hello it is kind of a question, its mainly scantime FUD right? running my file on my own machine triggers Windows Defender prompt that dropped file is malicious, any ideas how to bypass it on runtime?

**Comment by LNodesL** [comment]
Hi, sorry I do not offer support for bypassing, etc. If you have a technical question on how to protect your program in runtime so that third-parties cannot steal your data or invade your privacy, I can help out but please make sure to ask a specific coding question.
